
sudo: required
dist: trusty
language: ruby

rvm:
  - "2.1"

before_install:
  - sudo apt-get install -qq pkg-config fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
  - sudo apt-get install -y libfuse-dev

script:
  - bundle exec rake spec

cache:
  bundler: true
